
environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    platform: x64
    cname: msc
    qtver: 5.9
    qtbin: msvc2017_64
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    platform: x64
    cname: csc
    qtver: 5.9
    qtbin: msvc2017_64
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    platform: x86
    cname: mingw
    qtver: 5.9
    qtbin: mingw53_32
     
install:
  - set QTDIR=C:\Qt\%qtver%\%qtbin%\bin
  - set PATH=%QTDIR%;%PATH%
  - if %cname%==mingw set PATH=c:\qt\tools\mingw530_32\bin;c:\qt\tools\QtInstallerFramework\3.0\bin;%PATH%
  - if %cname%==mingw64 set PATH=c:\qt\tools\mingw730_64\bin;c:\qt\tools\QtInstallerFramework\3.0\bin;%PATH%
  - if %cname%==mingw set make=mingw32-make.exe
  - if %cname%==mingw64 set make=mingw32-make.exe
  - if not %cname%==mingw call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat"
  - if not %cname%==mingw set make=nmake.exe

build_script:
  - echo %cname%
  # *** build C++ with msc ***
  - cd CppLisp
  - if %cname%==msc MsBuild.exe /m /property:Configuration="Release" CppLisp.sln   
  - if %cname%==msc cd x64\release
  - if %cname%==msc fuel -v
  - if %cname%==msc 7z a fuel-lang-%cname%-bin.zip fuel.exe FuelInterpreter.dll FuelDebugger.dll Library\fuellib.fuel
  - if %cname%==msc 7z l fuel-lang-%cname%-bin.zip
  - if %cname%==msc appveyor PushArtifact fuel-lang-%cname%-bin.zip
  - if %cname%==msc copy fuel-lang-%cname%-bin.zip ..\..\..
  # *** execute C++ unit tests with msc ***
  - if %cname%==msc vstest.console CppLispInterpreterTests.dll  
  - if %cname%==msc cd ..\..
  
  # *** build C++ with mingw ***
  - if %cname%==mingw qmake -r CppLisp.pro 
  - if %cname%==mingw %make% -j 4
  - cd CppLisp
  - if %cname%==mingw cd release
  - if %cname%==mingw copy ..\..\CppLispInterpreter\release\FuelInterpreter.dll
  - if %cname%==mingw copy ..\..\CppLispDebugger\release\FuelDebugger.dll
  - if %cname%==mingw mkdir Library
  - if %cname%==mingw copy ..\..\..\Library\fuellib.fuel Library
  - if %cname%==mingw 7z a fuel-lang-%cname%-bin.zip fuel.exe FuelInterpreter.dll FuelDebugger.dll Library\fuellib.fuel
  - if %cname%==mingw 7z l fuel-lang-%cname%-bin.zip
  - if %cname%==mingw appveyor PushArtifact fuel-lang-%cname%-bin.zip
  - if %cname%==mingw copy fuel-lang-%cname%-bin.zip ..\..\..
  - if %cname%==mingw fuel.exe -v
  - if %cname%==mingw cd ..
  - cd ..
  # *** unit tests for C++ with mingw ***
  - cd QtLispInterpreterUnitTests
  - if %cname%==mingw qmake QtLispInterpreterUnitTests.pro 
  - if %cname%==mingw %make% -j 4
  - if %cname%==mingw cd release
  - if %cname%==mingw tst_qtlispinterpreterunitteststest.exe
  - if %cname%==mingw cd ..
  - cd ..\..
  
  # *** build C# with msc (and execute unit tests) ***
  - cd CsLisp
  - if %cname%==csc MsBuild.exe /m /property:Configuration="Release" CsLisp.sln   
  - if %cname%==csc cd bin\Release
  - if %cname%==csc fuel -v
  - if %cname%==csc 7z a fuel-lang-%cname%-bin.zip fuel.* fuel.exe.config FuelInterpreter.* FuelDebugger.* FuelCompiler.* Library\fuellib.fuel
  - if %cname%==csc 7z l fuel-lang-%cname%-bin.zip
  - if %cname%==csc appveyor PushArtifact fuel-lang-%cname%-bin.zip
  - if %cname%==csc copy fuel-lang-%cname%-bin.zip ..\..\..
  - cd ..
      
deploy:
  provider: GitHub
  auth_token:
    secure: wDEI4YGtqf1MiuNbtiv/zZ+rfuEmfO/PxfRfZC5gjtFDez3qDk6Vv9+auWwTstyZ
  artifact: fuel-lang-%cname%-bin.zip 
  draft: false
  prerelease: false
  on:
    #branch: master                 
    APPVEYOR_REPO_TAG: true        
    